[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.17"

[features]
seeds = false

[registry]
url = "https://api.apr.dev"

[scripts]
test = "pnpm test"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
smart_converter = "JDe51ZjpQ3tZzL6QTVPHt5VT5NzaDuJnrTmJJUFrC3vm"

[programs.devnet]
smart_converter = "JDe51ZjpQ3tZzL6QTVPHt5VT5NzaDuJnrTmJJUFrC3vm"

[programs.testnet]
smart_converter = "JDe51ZjpQ3tZzL6QTVPHt5VT5NzaDuJnrTmJJUFrC3vm"

[[test.genesis]]
address = "ALBSoqJrZeZZ423xWme5nozNcozCtMvDWTZZmQLMT3fp"
program = "tests/fixtures/albus.so"

#[test.validator]
#url = "https://api.devnet.solana.com"
#
#### Albus
#[[test.validator.clone]]
#address = "ALBSoqJrZeZZ423xWme5nozNcozCtMvDWTZZmQLMT3fp"
