[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
omnisol = "DMG9gp5VHPVpA3bst6yhC4L4D4aZiUjUTibVQGvJzpjy"

[programs.devnet]
omnisol = "DMG9gp5VHPVpA3bst6yhC4L4D4aZiUjUTibVQGvJzpjy"

[programs.testnet]
omnisol = "DMG9gp5VHPVpA3bst6yhC4L4D4aZiUjUTibVQGvJzpjy"
