[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
smart_converter = "BSP9GP7vACnCKxEXdqsDpGdnqMBafc6rtQozGwRkKqKH"

[programs.devnet]
smart_converter = "BSP9GP7vACnCKxEXdqsDpGdnqMBafc6rtQozGwRkKqKH"

[programs.testnet]
smart_converter = "BSP9GP7vACnCKxEXdqsDpGdnqMBafc6rtQozGwRkKqKH"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "target/deploy/metadata.so"

[[test.genesis]]
address = "ALBUSePbQQtw6WavFNyALeyL4ekBADRE28PQJovDDZQz"
program = "target/deploy/albus.so"
